### PR TITLE
Implement state-machine based fuzzing of Msg lists

### PR DESCRIPTION
**Pull request by jwoudenberg**
Hey @rtfeldman, this is an implementation of the idea by Evan (credit for API and example go to him). This repo seemed the best place to put something like this, until such a time this is all considered mature enough to be moved into elm-test itself perhaps.

### CODE REVIEW

**Comment by Janiczek** [comment]
From trying this out on the [vending machine example](https://github.com/Janiczek/elm-architecture-test/blob/state-machine/examples/vending-machine/tests/Tests.elm), I found one bug: **it doesn't generate empty `List Msg` / doesn't shrink properly**

I introduced a bug to [the tested model](https://github.com/Janiczek/elm-architecture-test/blob/state-machine/examples/vending-machine/src/VendingMachine.elm#L28-L30):
```diff
    case msg of
        AddCoins amount ->
-            { model | currentCoins = model.currentCoins + amount }
+            { model | currentCoins = model.currentCoins + 2 * amount }
```
In [the test](https://github.com/Janiczek/elm-architecture-test/blob/state-machine/examples/vending-machine/tests/Tests.elm#L87-L101) I generate a list of Msgs and a specific Msg (`AddCoins Int` here). The minimal inputs finding this bug would be `[]` and `AddCoins 1`.

The `randomWalk`-generated list was either never empty or is not shrinking properly; I got these sequences:
- `[AddCoins 1, Buy, TakeProduct]`
- `[Cancel]`

which together with the `AddCoins 1` specific Msg also provoke the bug, but aren't minimal.

**Comment by Janiczek** [comment]
One run with `Debug.log`-ed generated `Msg`s is [here for download](https://filebin.ca/3RVizvNaMJhq/msgs.txt) (130kB)

**Comment by jwoudenberg** [comment]
Hey @Janiczek, thanks for the report! I think the `[Cancel]` list actually is minimal, because it's the shortest path from the start state `NotEnoughMoney` to the single end state `Done`. Lifting `Done` to be the first state in the list would mark it the start state. This would make `[]` a valid path of the start state to an end state (because they're the same) and so it should show up as a shrunken value.

Perhaps the relevance of the first state in the list passed to `randomWalk` is to implicit in the current API?

With regards to the `[AddCoins 1, Buy, TakeProduct]` also showing up as a minimal value when `[Cancel]` is clearly shorter: this is an imperfection in the current shrinking strategy. The current shrinker only removes cycles, chains of messages starting and ending in the same state, because that was easy to build. The value `[AddCoins 1, Buy, TakeProduct]` contains no cycles and so is considered a minimal value by the current shrinker.

Ideally the shrinker would see that a `[ ..., AddCoins 1, Buy, TakeProduct, ... ]` occurring anywhere in the list of messages can be shrunk into `[ ..., Cancel, ... ]` but naively it seems to me that would require running a shortest path algorithm on arbitrary sublists of the full message list, which would be really slow. I think I might need to read a bit more on graphs to see if there's a better way to think about this. Or perhaps it's enough if the shrinker should always run a single shortest-path analysis on the full graph and ensure the result of that is always included as the smallest possible value.

**Comment by Janiczek** [comment]
As for `[Cancel]` and `[]` - oh, you're right, it always starts from the first `from`. Yeah, that might be too implicit. Maybe it would be a good idea to add that in explicitly (`startingStates : List StateName`)?

As for `[AddCoins 1, Buy, TakeProduct]` - I naively thought it would just start shrinking the list (dropping elements, shrinking elements) without regard to the state-transitions defined by user. What it does now probably makes more sense, but (for me) it means it doesn't find a minimal example. I'll have to think about this a bit too :)

All in all, it seems like this method will get you to bugs faster (walks paths that make sense application-wise) but will give you worse "minimal cases"; vs. plain `Fuzz.list (Fuzz.oneOf [msg1Fuzzer, msg2Fuzzer, msg3Fuzzer])` which will try more "nonsense" data but will shrink to the bare minimum. Maybe your generator + generic list shrinker would be the best of both worlds?

**Comment by jwoudenberg** [comment]
I think ultimately the shrinker and generator should obey by the same rules. If you create a fuzzer `odd = int |> map (\n -> n * 2 + 1)` you'd expect to only ever see odd numbers being passed into the test, regardless of whether it was the generator or shrinker producing them. `0` might be the smallest int, but it's not the smallest odd number and so we shouldn't (and don't) shrink all the way down to it. What I think is cool about this is that it allows people to use fuzzers without having to know about shrinking.

Staying with the odd numbers example: shrinkers will try to find the smallest value that fails the test. Perhaps `0` fails the test because it's an even number, not because of whatever bug led to the shrink being started in the first place. Reporting back to the user that `0` didn't work is ultimately useless information to the user. They already knew that, which is why they created a fuzzer to generate odd numbers! In the same way I feel we shouldn't break the constraints the user provided on the lists of messages.

In your specific case perhaps your `Done` state is misnamed and is really a `Start` state. After cancelling / buying an item you return back in that state (because you could buy another item). Have you tried putting it at the top of the list?

**Comment by Janiczek** [comment]
Ah, so it's a matter of modeling the state transitions properly. I tried the `Start` idea and putting it to the front:
```elm
type StateName
    = Start
    | NotEnoughMoney
    | EnoughMoney
    | Vended

msgsFuzzer : Fuzzer (List Msg)
msgsFuzzer =
    randomWalk
        [ from Start
            [ end 3
            , step 1 TakeProduct Start
            , step 1 Cancel Start
            , step 1 Buy Start
            , step 7 (AddCoins 1) NotEnoughMoney
            , step 2 (AddCoins 25) EnoughMoney
            ]
        , from NotEnoughMoney
            [ step 1 TakeProduct NotEnoughMoney
            , step 2 Cancel Start
            , step 2 Buy NotEnoughMoney
            , step 5 (AddCoins 1) NotEnoughMoney
            , step 3 (AddCoins 25) EnoughMoney
            ]
        , from EnoughMoney
            [ step 1 TakeProduct EnoughMoney
            , step 1 Cancel Start
            , step 10 Buy Vended
            , step 1 (AddCoins 1) EnoughMoney
            ]
        , from Vended
            [ step 10 TakeProduct Start
            , step 3 TakeProduct NotEnoughMoney
            , step 1 TakeProduct EnoughMoney
            , step 1 Cancel Vended
            , step 1 Buy Vended
            , step 1 (AddCoins 1) Vended
            ]
        ]
```
The result: it **catched the bug** with input `[]` (ie. the minimal example!), yay! :tada:

----

I tried a different bug:
```diff
    case msg of
        -- ...
        Buy ->
-           if model.currentCoins >= model.productPrice then
-               { model
-                   | currentCoins = 0
-                   , isProductVended = True
-               }
-           else
-               model
+           model
```
Its minimal example should be `[AddCoins 25]` (when testing `Buy` as a last, constant message after the random ones), but of course in my state machine description the `EnoughMoney` state isn't an end state, so it finds an end state with `[AddCoins 25, Buy, TakeProduct]`.

If I give all states an ending probability, I **do** get the minimal example, among other non-minimal examples:
```
[AddCoins 25]
[AddCoins 25, Buy]
[AddCoins 25, Buy, TakeProduct]
[AddCoins 25, Buy, TakeProduct, AddCoins 1]
[AddCoins 1, AddCoins 25]
[AddCoins 1, AddCoins 25, Buy]
[AddCoins 1, AddCoins 25, Buy, TakeProduct]
[AddCoins 1, AddCoins 25, Buy, TakeProduct, AddCoins 1]
```
Some of your ideas about shortest-path algorithm could maybe be of benefit here :)

----

**The conclusion for me**:
- While I agree with you in the general case of shrinking sticking to the constraints for generating, I still think that, for the `List Msg` case, trying to shrink a failure aggresively would be of value. Basically, my position is that **if a test fails but it's a nonsense value** (your example: fails on 0 while only odd numbers make sense), **then that's a problem with the test** (I use [`msgTestWithPrecondition`](https://github.com/Janiczek/elm-architecture-test/blob/master/examples/vending-machine/tests/Tests.elm#L97) to deal with that). I might prove myself wrong after trying to implement these tests for something more complex, eg. [elm-spa-example](https://github.com/rtfeldman/elm-spa-example).
- It would be beneficial to have some "best practices" for writing this kind of state machine specification, because banging it out thoughtlessly leads to the problems I experienced and you helped me with in this issue :)
- Overall, **it's very nice!** On the spectrum from "Totally random Msgs" (1) to "Msgs dependent on current Model" (2), it's somewhere in the middle. I think I'll still try to create a `Fuzz.custom` version of (2) and see where that leads me, but this is definitely usable. Thank you :)

**Comment by Janiczek** [comment]
A thought: does it make sense to make the user specify end states? The user interaction with the app can be broken "in the middle", ie. the `[AddCoins 25, Buy, TakeProduct]` example where I actually needed `[AddCoins 25]`

**Comment by jwoudenberg** [comment]
@Janiczek The user can specify end states! All states with an `end` in it are an end state.

Will get back to your larger response too later when I have some more time :).

**Comment by Janiczek** [comment]
Yes, my point was: shouldn't all states be end states?

**Comment by jwoudenberg** [comment]
> Yes, my point was: shouldn't all states be end states?

I don't think that should be the default. If you only make some general assertions against the model that should always hold than definitely you could stop whenever you want. But if you use this fuzzer to get your model into a particular state and then want to make assertions specific to that state then you need to be sure the list fuzzer delivers you where you want to go.

> If I give all states an ending probability, I do get the minimal example, among other non-minimal examples: <example>

It's good you bring this up. Fixing the other non-minimal cases you listed there requires the much easier shrinker capability of being able to stop early on an and step if one is encountered, in addition to being able to remove cycles.

> Basically, my position is that if a test fails but it's a nonsense value (your example: fails on 0 while only odd numbers make sense), then that's a problem with the test

I don't follow your meaning here, sorry. Could you explain it to me in a different way?

> It would be beneficial to have some "best practices" for writing this kind of state machine specification, because banging it out thoughtlessly leads to the problems I experienced and you helped me with in this issue :)

Definitely!

> Overall, it's very nice! On the spectrum from "Totally random Msgs" (1) to "Msgs dependent on current Model" (2), it's somewhere in the middle. I think I'll still try to create a Fuzz.custom version of (2) and see where that leads me, but this is definitely usable. Thank you :)

Thanks! One note on that last point: if generic list shrinking behaviour is what you want then creating that `Fuzz.custom` for your use case might be easy. You just build the `Generator` part using `Generator.andThen` and then you add the existing list shrinker.

**Comment by Janiczek** [comment]
> But if you use this fuzzer to get your model into a particular state and then want to make assertions specific to that state then you need to be sure the list fuzzer delivers you where you want to go.

So, when does that situation happen? Does it ever happen?
- So far we have one precedent: the vending machine - and there we don't want that.
- But again, we might find out that we *do* when testing `elm-todomvc` or `elm-spa-example` :)

Let's say the app is buggy while writing an username to a login field. That's probably not an end state, but I still want to test that. To have `[SetUsername "foo"]` as an minimal example instead of `[SetUsername "foo", SetPassword "bar", Submit, Logout]`, I'd have to make the state after `SetUsername` an end state.

Basically, I think you want to test the model at well-defined steps, while I want to test the model at any step.

> I don't follow your meaning here, sorry. Could you explain it to me in a different way?

To recap, we're dealing with shrinking strategies (whether to shrink to meaningful state machine steps, or just randomly throw out Msgs)

Let's say I got `[AddCoins 1, AddCoins 25, TakeProduct, Buy]` and that provokes a bug n.1 ("`Buy` doesn't buy with enough money").
- If that got shrunk to `[Buy]` (again, "`Buy` doesn't buy with enough money"), then that's an error with the test (`Buy` should only buy when the machine has enough coins, but the test doesn't reflect that).
- If, on the other hand, it got shrunk to `[AddCoins 1, Buy]` (different bug, let's say "`Buy` buys with not enough money"), I don't mind that - it just showed me different bug. No problem!

In your example ("`0` fails the test, but we only wanted to test odd numbers") - well then, why not make the test pass on even numbers?

> One note on that last point: ...snip...

Great, I will try that. Thank you!

**Comment by jwoudenberg** [comment]
Hey @Janiczek, I fixed the case you had previously where every state was an end state, where it didn't consistently shrink down to the empty list as a smallest case.

> Basically, I think you want to test the model at well-defined steps, while I want to test the model at any step.

Exactly! The current API supports both of these but if we'd let every state be an end state, only 'your 'use case would be supported.

As an example of 'my' use case: Suppose you want to try a lot of different options on this login field, so you create a fuzzer (separately from the code in this PR) which generates all the possible `SetUsername String` messages. You could use this list of Msg fuzzer to create a chain leading towards the login page, then append the fuzzed `SetUsername` msg at the end and run that through your update function.

> In your example ("0 fails the test, but we only wanted to test odd numbers") - well then, why not make the test pass on even numbers?

Thanks for rephrasing that for me! To answer your question:

- Because I've already specified once I don't want even numbers, if I need to specify the same constraints in two places it increases the likelihood of introducing bugs into my tests.
- It's unintuitive, because the Fuzzer doesn't seem to obey my specification. Using Fuzz.Msg in a predictable manner would require users to know shrinking exists, roughly what it does, and that it follows different rules than generation. That's a lot of complexity that I'd prefer to keep out of the docs.

**Comment by Janiczek** [comment]
@jwoudenberg Your arguments are good enough for me :) I kinda see where you're coming from now. (I still want to try other APIs, but - yeah, this is great!)

**Comment by jwoudenberg** [comment]
Published this in a separate package for now: https://github.com/jwoudenberg/elm-test-experimental

Open to aggregating this with another package elsewhere at some point, but let's try it out a bit first.

**Pull request closed without merging**
